# Build settings
markdown: kramdown
repository: rubyreferences/rubychanges
title: Ruby Changes
url: https://rubyreferences.github.io/rubychanges/

exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'tmp']

# plugins:
#   - jekyll-readme-index
